# Generated by Django 5.2.4 on 2025-07-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40, verbose_name="Nombre")),
                ("color", models.CharField(max_length=40, verbose_name="Color")),
            ],
        ),
    ]
